version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      PYTHONIOENCODING: utf-8
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
    command: flask run --host 0.0.0.0
    networks:
      - movie-network  
    depends_on:
      - db

  db:
    container_name: postgres_Filmes
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Filmes
    volumes:
      - dbmovies_data_movies:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - movie-network  

networks:
  movie-network:
    external: true  

volumes:
  dbmovies_data_movies:
